apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
  labels:
    type: local
    name: plex-config
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.volumes.config }}"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-transcode
  labels:
    type: local
    name: plex-transcode
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.volumes.transcode }}"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-data
  labels:
    type: local
    name: plex-data
  selector:
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.volumes.data }}"
