apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-plex.fullname" . }}
  labels:
    {{- include "kube-plex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: 32400
      protocol: TCP
      name: pms
  selector:
    {{- include "kube-plex.selectorLabels" . | nindent 4 }}
