---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex-media-server
  namespace: plex
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: glob:1.19.2.2737:w-*
spec:
  releaseName: plex
  chart:
    git: ssh://git@github.com/fluxcd/flux-get-started
    ref: master
    path: charts/plex
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.19.2.2737-b69929dab
    service:
      type: NodePort
