---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:1.19.2.2737-*
spec:
  releaseName: plex
  chart:
    git: ssh://git@github.com/fluxcd/flux-get-started
    ref: master
    path: charts/plex
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.19.2.2737-b69929dab
      env:
        plexUid: "1000"
        plexGid: "44"
        tz: "Australia/Melbourne"
    service:
      type: NodePort
    volumes:
      config: "/var/lib/plexmediaserver"
      transcode: "/tmp"
      data: "/home/dab/videos"
