apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-data
  annotations:
    fluxcd.io/automated: "true"
  labels:
    type: local
    name: jira-data
spec:
  storageClassName: jira-data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/k8s/jira-data
