apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-data
  labels:
    type: local
    name: jira-data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"
